import { useState, useEffect } from 'react';
import './App.css';
import { useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';

function HandleBooking() {
    const { showId } = useParams(); 
    const [seats, setSeats] = useState([]);
    // 1. Initialize as an empty array
    const [selectedSeats, setSelectedSeats] = useState([]); 
    const navigate = useNavigate();

    const toggleSeatSelection = (seat) => {
        if (seat.status !== 'AVAILABLE') return;

        setSelectedSeats((prev) => {
            // Ensure prev is an array before calling find
            const isSelected = prev.find(s => s.id === seat.id);
            if (isSelected) {
                return prev.filter(s => s.id !== seat.id);
            } else {
                return [...prev, seat];
            }
        });
    };

    useEffect(() => {
        console.log("Value of showId is ::: ");
        console.log(showId);
        const fetchSeats = async () => {
            try {
                // Ensure we use the showId from the URL
                const response = await axios.get(`/api/v1/seats/show/${showId}`);
                console.log("Response for the show call .. ");
                console.log(response);
                setSeats(response.data);
            } catch (err) {
                console.error("Could not load seats", err);
            }
        };
        if (showId) fetchSeats();
    }, [showId]);
    
    const handlePayment = async () => {
    try {
        // 1. Call your Java backend to create the Razorpay Order
        const amount = selectedSeats.length * 200; // Example price
        const response = await axios.post(`/api/v1/payments/create-order`, {
            amount: amount,
            screeningId: id
        });

        const orderData = response.data; // This is the string/object from your Service

        // 2. Configure Razorpay Options
        const options = {
            key: "YOUR_RAZORPAY_KEY_ID", // Best to get this from backend too
            amount: orderData.amount, 
            currency: "INR",
            name: "BookMyShow Clone",
            description: "Movie Ticket Booking",
            order_id: orderData.id, // The ID generated by your RazorpayService
            handler: function (response) {
                // This runs after successful payment
                alert("Payment Successful! Payment ID: " + response.razorpay_payment_id);
                confirmBooking(response.razorpay_payment_id);
            },
            prefill: {
                name: "User Name",
                email: "user@example.com",
                contact: "9999999999"
            },
            theme: {
                color: "#3399cc"
            }
        };

        // 3. Open the Popup
        const rzp = new window.Razorpay(options);
        rzp.open();

    } catch (error) {
        console.error("Payment failed", error);
    }
};

    return (
        <div className="booking-page">
            {/* ... Screen Header ... */}

            <div className="seat-container">
                {seats.map((seat) => (
                    <button
                        key={seat.id}
                        onClick={() => toggleSeatSelection(seat)}
                        className={`seat ${seat.status.toLowerCase()} ${
                            // 2. Check if this seat is in the selection array
                            selectedSeats.find(s => s.id === seat.id) ? 'selected' : ''
                        }`}
                    >
                        {seat.seatNumber || seat.id}
                    </button>
                ))}
            </div>

            {/* 3. Check for array length to show the footer */}
            {selectedSeats.length > 0 && (
    <div className="payment-bar">
        <div className="payment-details">
            <span className="selected-count">
                {selectedSeats.length} Seat(s) Selected
            </span>
            <span className="total-amount">
                Total: ₹{selectedSeats.length * 200}
            </span>
        </div>
        <button className="pay-btn-pop" onClick={handlePayment}>
            Proceed to Pay
        </button>
    </div>
)}
        </div>
    );
}

export default HandleBooking;